[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "quanhoang55", email = "quanhoang1026@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "uvicorn>=0.54.0",
    "websockets>=13.0",
    "opencv-python>=4.10",
    "ultralytics>=8.4",
    "numpy>=2.0",
]

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
